// <auto-generated />
namespace LNU.Scheduler.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Stablemodels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Stablemodels));
        
        string IMigrationMetadata.Id
        {
            get { return "201711182214105_Stable models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
